---
title: "Assignment_b1"
author: Ariel Rosen
date: November/4/2022
output: github_document
---

```{r}
#Loading required packages 
library(tidyverse)
library(dplyr)
library(gapminder)
library(testthat)
```

**Exercises 1 and 2: Make a Function and Document your Function**

```{r}
#' mean_median 
#' This function calculates the mean and median of a group of numeric variables. 
#'
#' @param x is greater than or equal to 2 numeric variables. 
#'
#' @return a vector containing the mean and median of the variables. 
#' 
#' @examples: #Using the function to calculate the mean and median gdp per capita in the gapminder data set
(mean_median_gdpPercap <- mean_median(gapminder$gdpPercap))

mean_median <-function(x) {
  stopifnot(is.numeric(x))
  mean <-mean(x)
  median <-median(x)
  result <- (c(mean,median))
}

```

**Exercise 3: Include Examples**

```{r}
#Using the function to calculate the mean and median gdp per capita in the gapminder data set
(mean_median_gdpPercap <- mean_median(gapminder$gdpPercap))

#Using the function to calculate my mean and median grade percentage in STAT 545A
(mean_median_STAT545A <- mean_median(c(100, 100, 67, 100, 95.5, 100)))

```

```{r}
#Throwing an error for applying the function to non-numerical variables
(mean_median_error <- mean_median(gapminder$country))
(mean_median_error_2 <- mean_median(c(TRUE, FALSE, TRUE, TRUE)))
```

**Exercise 4: Test the function**

```{r}
#Making a dataframe with NAs to test the function
(df <- data.frame(x = c(1,2,3,6,8,12,15,"NA"), y = c(5,6,7,22,"NA",122,67,9)))
```

```{r}
test_that("Testing mean and median function",{
  expect_error(mean_median(gapminder[c('lifeExp', 'pop')]))
  expect_equal(mean_median(gapminder$year), (c(mean(gapminder$year),median(gapminder$year))))
  expect_error(mean_median(df$y))
})
```
